import Image from "next/image";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import About from "@/components/About";
import Footer from "@/components/Footer";
import Partners from "@/components/Partners";
import Services from "@/components/Services";


export default function Home() {
  return (
    <>
      <Head>
        <title>Everclean</title>
        <meta name="keywords" content='Everclean' />
        <meta name="description" content="EverClean Services is at the forefront of transforming smart city cleaning for governments and residents alike through its cutting-edge automated deep cleaning solutions. By streamlining the meticulous cleaning of streets, roads, and highways through advanced vacuuming technology, EverClean empowers governments to uphold pristine urban environments free from the debris generated by daily activities. Our mission is to redefine cleanliness standards, ensuring cities are not only visually appealing but also conducive to the well-being of their inhabitants." />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className='w-full h-screen font-bodyFont bg-white text-[#000] overflow-x-hidden overflow-y-scroll scrollbar scrollbar-track-textDark/20 scrollbar-thumb-textDark/60 '
      >
        <Navbar />
        <Banner />
        <About />
        <Services />
        <Partners />
        <Footer />
      </main>
    </>
  );
}
